[build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 app:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
rootDirectory = "backend"
