[phases.setup]
nixPkgs = ["python310", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir tensorflow==2.18.0",
    "pip install --no-cache-dir keras==3.5.0", 
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 1 app:app"
